# Generated by Django 3.1.7 on 2021-04-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pectoral', '胸筋'), ('abs', '腹筋'), ('spine', '背筋'), ('run', 'ランニング')], max_length=100)),
                ('date', models.DateField(verbose_name='日付')),
            ],
        ),
    ]
