# Generated by Django 3.1.7 on 2021-04-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mustlecalendarapp', '0003_auto_20210403_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='category_abs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='category_pectoral',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='category_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='category_spine',
            field=models.BooleanField(default=False),
        ),
    ]
