# Generated by Django 3.1.7 on 2021-04-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mustlecalendarapp', '0007_auto_20210403_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='place',
            field=models.CharField(choices=[('house', '家'), ('gym', 'ジ')], default='house', max_length=100, verbose_name='場所'),
        ),
    ]
