# Generated by Django 3.1.7 on 2021-04-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mustlecalendarapp', '0008_auto_20210403_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='id',
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(primary_key=True, serialize=False, verbose_name='日付'),
        ),
    ]
